AWSTemplateFormatVersion: '2010-09-09'
Description: |-
  CloudFormation template to demonstrate a step function workflow
  Once the objects have been scanned, the step function will be invoked

Resources:
  SourceBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-source-bucket'
      VersioningConfiguration:
        Status: Enabled
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  DestinationBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-destination-bucket'
      VersioningConfiguration:
        Status: Enabled

  StepFunctionsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: S3Actions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                  - 's3:GetObjectTagging'
                  - 's3:PutObjectTagging'
                  - 's3:GetObjectVersionTagging'
                  - 's3:GetObjectAttributes'
                Resource: 
                  - !GetAtt SourceBucket.Arn
                  - !Join ['', [!GetAtt SourceBucket.Arn, '/*']]
                  - !GetAtt DestinationBucket.Arn
                  - !Join ['', [!GetAtt DestinationBucket.Arn, '/*']]

  S3CopyDeleteStateMachine:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      StateMachineName: !Sub '${AWS::StackName}-state-machine'
      RoleArn: !GetAtt StepFunctionsRole.Arn
      DefinitionString: !Sub
        - |-
          {
            "Comment": "S3 Copy and Delete Workflow",
            "StartAt": "GetObjectTagging",
            "States": {
              "GetObjectTagging": {
                "Type": "Task",
                "Parameters": {
                  "Bucket.$": "$.detail.bucket.name",
                  "Key.$": "$.detail.object.key"
                },
                "Resource": "arn:aws:states:::aws-sdk:s3:getObjectTagging",
                "Next": "CheckScanResultTag",
                "ResultSelector": {
                  "ScanResultTag.$": "$.TagSet[?(@.Key=='ScanResult')]"
                },
                "ResultPath": "$.ObjectTags"
              },
              "CheckScanResultTag": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.ObjectTags.ScanResultTag[0].Value",
                  "StringEquals": "CLEAN",
                  "Next": "CopyS3Object"
                }
              ],
              "Default": "SkipProcessing"
            },
              "CopyS3Object": {
                "Type": "Task",
                "Resource": "arn:aws:states:::aws-sdk:s3:copyObject",
                "Parameters": {
                  "Bucket": "${DestinationBucketName}",
                  "CopySource.$": "States.Format('{}/{}', $.detail.bucket.name, $.detail.object.key)",
                  "Key.$": "$.detail.object.key"
                },
                "Next": "VerifyMD5Checksum",
                "ResultPath": "$.CopyS3Object",
                "ResultSelector": {
                  "Etag.$": "States.StringToJson($.CopyObjectResult.ETag)"
                }                
              },
              "VerifyMD5Checksum": {
                "Type": "Choice",
                "Choices": [
                  {
                    "Variable": "$.detail.object.etag",
                    "StringEqualsPath": "$.CopyS3Object.Etag",
                    "Next": "DeleteSourceObject"
                  }
                ],
                "Default": "CopyFailed"
              },
              "DeleteSourceObject": {
                "Type": "Task",
                "Resource": "arn:aws:states:::aws-sdk:s3:deleteObject",
                "Parameters": {
                  "Bucket.$": "$.detail.bucket.name",
                  "Key.$": "$.detail.object.key"
                },
                "End": true
              },
              "CopyFailed": {
                "Type": "Fail",
                "Cause": "MD5 checksum verification failed",
                "Error": "ChecksumMismatch"
              },
              "SkipProcessing": {
                "Type": "Succeed"
              }              
            }
          }
        - {DestinationBucketName: !Ref DestinationBucket}

  EventBridgeRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: InvokeStepFunction
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'states:StartExecution'
                Resource: !Ref S3CopyDeleteStateMachine

  EventBridgeRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: "Rule to trigger Step Function when Object Tags are added to S3 Object"
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - "Object Tags Added"
        detail:
          bucket:
            name:
              - !Ref SourceBucket
      State: ENABLED
      Targets:
        - Arn: !Ref S3CopyDeleteStateMachine
          Id: "TriggerStepFunction"
          RoleArn: !GetAtt EventBridgeRole.Arn

Outputs:
  SourceBucketName:
    Description: "Name of the source S3 bucket"
    Value: !Ref SourceBucket
  DestinationBucketName:
    Description: "Name of the destination S3 bucket"
    Value: !Ref DestinationBucket
  StateMachineArn:
    Description: "ARN of the Step Functions state machine"
    Value: !Ref S3CopyDeleteStateMachine
