---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket'
Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 Bucket
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

